### ISSUE TITLE
At Step 2 : Open Storenames GUI and save storenames "UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character" error

### ISSUE THREAD

**Issue by baris-61** [LernerLab/GuPPy#111]
Full console leading to the error:
Input Parameters File Saved.
['C:\\Users\\baris\\Desktop\\Doric test 4 Aralık 2024\\Doric test 4 Aralık 2024']
2024-12-05 12:29:10,286 If it exists, importing either NPM or Doric or csv file based on the structure of file
2024-12-05 12:29:10,288 'mbcs' codec can't encode characters in position 0--1: invalid character
Traceback (most recent call last):
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\saveStoresList.py", line 877, in execute
    event_name, flag = import_np_doric_csv(filepath, isosbestic_control, num_ch)
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\saveStoresList.py", line 661, in import_np_doric_csv
    key_names = read_doric(path[i])
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\saveStoresList.py", line 628, in read_doric
    with h5py.File(filepath, 'r') as f:
  File "D:\Anaconda\envs\guppy\lib\site-packages\h5py\_hl\files.py", line 395, in __init__
    name = filename_encode(name)
  File "D:\Anaconda\envs\guppy\lib\site-packages\h5py\_hl\compat.py", line 114, in filename_encode
    return filename.encode(WINDOWS_ENCODING, "strict")
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x000001E2EB9B8CA0>>, <Task finished name='Task-182' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at D:\Anaconda\envs\guppy\lib\site-packages\bokeh\server\session.py:51> exception=UnicodeEncodeError('mbcs', 'C:\\Users\\baris\\Desktop\\Doric test 4 Aralık 2024\\Doric test 4 Aralık 2024\\BFPD_Acq_0001.doric', 0, 0, 'invalid character')>)
Traceback (most recent call last):
  File "D:\Anaconda\envs\guppy\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "D:\Anaconda\envs\guppy\lib\site-packages\tornado\ioloop.py", line 767, in _discard_future_result
    future.result()
  File "D:\Anaconda\envs\guppy\lib\site-packages\bokeh\server\session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "D:\Anaconda\envs\guppy\lib\site-packages\tornado\gen.py", line 191, in wrapper
    result = func(*args, **kwargs)
  File "D:\Anaconda\envs\guppy\lib\site-packages\panel\reactive.py", line 249, in _change_coroutine
    self._change_event(doc)
  File "D:\Anaconda\envs\guppy\lib\site-packages\panel\reactive.py", line 259, in _change_event
    self._process_events(events)
  File "D:\Anaconda\envs\guppy\lib\site-packages\panel\reactive.py", line 242, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "D:\Anaconda\envs\guppy\lib\site-packages\param\parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "D:\Anaconda\envs\guppy\lib\site-packages\param\parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "D:\Anaconda\envs\guppy\lib\site-packages\param\parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\savingInputParameters.ipynb", line 441, in onclickStoresList
    "def onclickStoresList(event=None):\n",
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\saveStoresList.py", line 882, in execute
    raise e
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\saveStoresList.py", line 877, in execute
    event_name, flag = import_np_doric_csv(filepath, isosbestic_control, num_ch)
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\saveStoresList.py", line 661, in import_np_doric_csv
    key_names = read_doric(path[i])
  File "C:\Users\baris\Desktop\YediTepe\GuPPy-main\GuPPy\saveStoresList.py", line 628, in read_doric
    with h5py.File(filepath, 'r') as f:
  File "D:\Anaconda\envs\guppy\lib\site-packages\h5py\_hl\files.py", line 395, in __init__
    name = filename_encode(name)
  File "D:\Anaconda\envs\guppy\lib\site-packages\h5py\_hl\compat.py", line 114, in filename_encode
    return filename.encode(WINDOWS_ENCODING, "strict")
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

**Comment by baris-61** [comment]
There are only 3 .doric files and GuPPyParamtersUsed.json in the file

**Comment by venus-sherathiya** [comment]
is this happening to all of your data ? Can you please send me your data ? I can re-run the analysis and see what's happening ?

**Comment by baris-61** [comment]
these .doric files are from our latest doric data and these files are the
most recent files, this problem started at these files. (there are no more
files)
 BFPD_Acq_0000.doric
<https://drive.google.com/file/d/1crUP07Yp817v4AlIsZ4g8UzlMUqLI8Vu/view?usp=drive_web>
 BFPD_Acq_0001.doric
<https://drive.google.com/file/d/1wHeYUN26e1Ezbo_Kb0RHGvA-cfUb2_QI/view?usp=drive_web>
 BFPD_Acq_0002.doric
<https://drive.google.com/file/d/1Fk7I8SsDAwKVlTy0EQtK8hU9My_ExK5B/view?usp=drive_web>

Venus Sherathiya ***@***.***>, 9 Ara 2024 Pzt, 18:41
tarihinde şunu yazdı:

**Comment by venus-sherathiya** [comment]
Can you please give me access to these files ? I sent you access request

**Comment by baris-61** [comment]
I gave you Access

**Comment by venus-sherathiya** [comment]
Are all three .doric files corresponds to one recording session ? or different recording session ?

**Comment by venus-sherathiya** [comment]
Were you able to solve this issue ?

**Comment by baris-61** [comment]
I couldn't check about this issue further due to our doric is bricked
during a software update, because of this reason I couldn't answer you, I'm
sorry about that.
When it is fixed I will try it again to check if this issue was caused by
old software problems.

Venus Sherathiya ***@***.***>, 15 Ara 2024 Paz, 20:25
tarihinde şunu yazdı:

**Comment by pauladkisson** [comment]
Thank you for reporting this issue @baris-61. 

We recently made a beta release of an updated version of Guppy that might have fixed this problem (installation instructions [here](https://guppy.readthedocs.io/installation.html)). Have you had a chance to try that one out? If so, do you get the same error? If the error persists, it would be very helpful if you could re-share the example data with me.
