### ISSUE TITLE
No Storenames extracted for Neurophotometrics file

### ISSUE THREAD

**Issue by evaghreins** [LernerLab/GuPPy#25]
I have neurophotometrics data (saved in .csv files - one for the timestamp, one that contains the timeframe and interleaved signal and isosbestic) that I am trying to analyse via GuPPy but when I open the Storenames GUI after selecting these files, no storenames appear, as if the file has not been read. I've checked and the layout of the .csv files is the same as the example data provided. 

Moreover, if I drag over a folder to 'selected files' that contains my .csv files (instead of the individual files) then I get the following error and no Storename Gui opens up. 

tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fce4dadacf8>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/bokeh/server/session.py:51> exception=ValueError("could not convert string to float: 'H'",)>)
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1152, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/bokeh/server/session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/tornado/gen.py", line 191, in wrapper
    result = func(*args, **kwargs)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/panel/reactive.py", line 249, in _change_coroutine
    self._change_event(doc)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/panel/reactive.py", line 259, in _change_event
    self._process_events(events)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/panel/reactive.py", line 242, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/param/parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/param/parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/evaguerrero/GuPPy-main/GuPPy/savingInputParameters.ipynb", line 243, in onclickStoresList
    "\n",
  File "/Users/evaguerrero/GuPPy-main/GuPPy/saveStoresList.py", line 665, in execute
    event_name, flag = import_np_csv(filepath, isosbestic_control, num_ch)
  File "/Users/evaguerrero/GuPPy-main/GuPPy/saveStoresList.py", line 484, in import_np_csv
    df = pd.read_csv(path[i], dtype=float)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/Users/evaguerrero/opt/anaconda3/envs/guppy/lib/python3.6/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 860, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 952, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1084, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1158, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: 'H'

**Comment by venus-sherathiya** [comment]
I replied on Gitter chat room. So, closing this issue here
i will try my best to help you out
