### ISSUE TITLE
GupPY v1.2 doesn't run, .dll not found

### ISSUE THREAD

**Issue by MannyEsguerra** [LernerLab/GuPPy#28]
I updated to v1.2 by extracting the .zip.  Also deleted my old anaconda environment and rebuilt it so:

```
conda create --name guppy --file spec_file_windows10.txt
conda activate guppy
conda install -c anaconda ipykernel
python -m ipykernel install --user --name=guppy
```

Now when I try to start the server I get this ".dll not found" error:

```
(guppy) D:\Packages\zOLD VERSIONS\GuPPy-main OLD\GuPPy-main\GuPPy>panel serve --show savingInputParameters.ipynb
2022-11-15 15:12:06,166 Starting Bokeh server version 2.4.3 (running on Tornado 6.1)
2022-11-15 15:12:06,166 User authentication hooks NOT provided (default user enabled)
2022-11-15 15:12:06,166 Bokeh app running at: http://localhost:5006/savingInputParameters
2022-11-15 15:12:06,166 Starting Bokeh server with process id: 6804
2022-11-15 15:12:06,435 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x000001C0C8DB2C70>: Could not find module 'C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\scipy\.libs\libbanded5x.4LIW6FJ2MYAF374XJSSB2KHHIEBRW45R.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
File '__init__.py', line 373, in __init__:
self._handle = _dlopen(self._name, mode) Traceback (most recent call last):
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\bokeh\application\handlers\code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "D:\Packages\zOLD VERSIONS\GuPPy-main OLD\GuPPy-main\GuPPy\savingInputParameters.ipynb", line 15, in <module>
    "import numpy as np\n",
  File "D:\Packages\zOLD VERSIONS\GuPPy-main OLD\GuPPy-main\GuPPy\preprocess.py", line 11, in <module>
    from scipy import signal as ss
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\scipy\__init__.py", line 144, in <module>
    from . import _distributor_init
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\scipy\_distributor_init.py", line 59, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\scipy\.libs\libbanded5x.4LIW6FJ2MYAF374XJSSB2KHHIEBRW45R.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

2022-11-15 15:12:06,611 WebSocket connection opened
2022-11-15 15:12:06,612 ServerConnection created
````
```

**Comment by MannyEsguerra** [comment]
Update: with Venus's help, we found that this happened because I deleted the Guppy environment from inside Anaconda Navigator. Using from the terminal `conda remove --name guppy --all ` and reinstalling Guppy made it work. 

We have a new issue now. Analyzing data that worked in previous versions now throws this error
```
Traceback (most recent call last):
  File "readTevTsq.py", line 409, in <module>
    readRawData(json.loads(sys.argv[1]))
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by venus-sherathiya** [comment]
Please use the updated code from github
GuPPy-v1.2.0 works without any errors !!

**Comment by venus-sherathiya** [comment]
Closing issue because it is fixed

**Comment by venus-sherathiya** [comment]
Closing issue because it is fixed
