### ISSUE TITLE
Can't read raw data 

### ISSUE THREAD

**Issue by Ossamaghenissa** [LernerLab/GuPPy#30]
Hey, 
I just installed GuPPy and tried to get the hang of it using the sample CSV files. 
Unfortunatly, even after double checking every step of the process, I get the error message : 

"Traceback (most recent call last):
  File "readTevTsq.py", line 409, in <module>
    readRawData(json.loads(sys.argv[1]))
  File "C:\Users\Massa\Anaconda3\envs\guppy\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Massa\Anaconda3\envs\guppy\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Massa\Anaconda3\envs\guppy\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

I'm new to this so thanks in advance for your time.

**Comment by venus-sherathiya** [comment]
it's is fixed now.
Please use the updated the code from github.

**Comment by venus-sherathiya** [comment]
Closing issue because it is fixed
