### ISSUE TITLE
Error "Column names should be timestamps, data and sampling_rate (all lower-cases)"

### ISSUE THREAD

**Issue by goutaudi** [LernerLab/GuPPy#46]
Hello, 

We are currently trying to use GuPPy to analyze our Doric data. We have two signal (480nm and 405nm) with four DIO. I extract the data from doric neuroscience in .CSV 

We obtain two files for the signal that we named : 
- RLA8_signal_DA.csv
- RLA8_control_DA.csv
In these files, on the first line we have : Time, Value (see picture1). 
![Picture1](https://github.com/LernerLab/GuPPy/assets/138767133/ef5251af-c06a-4e86-975d-3767a07988df)
We change Time by timestamps, value by data and we add the sampling_rate (see picture 2). We save as type CSV (Comma delimited).
![Picture2](https://github.com/LernerLab/GuPPy/assets/138767133/dc6f62c0-14a1-4e8b-b375-505eb216f7f8)

I obtain four files for the 4 DIO, that I named : 
- RLA8_DIO01_IN.csv
- RLA8_DIO02_IN.csv
- RLA8_DIO03_IN.csv
- RLA8_DIO04_IN.csv
In these files, on the first line we have : DIOXX, Time (see picture3). 
![Picture3](https://github.com/LernerLab/GuPPy/assets/138767133/ea6bcc6a-d478-4c2d-a2df-a90f4da3ff6f)

We change Time by timestamps. As we are interested only by the beginning of the behavior (we keep the timestamps where the DIO switch from 0 to 1), we remove all the timestamps useless using a Matlab script. We also remove the DIOXX column to keep only the timestamp column (see picture 4).
![Picture4](https://github.com/LernerLab/GuPPy/assets/138767133/9d30e1e8-e0bc-466b-837d-16d46b0fc977)

Then we put the 6 files in a folder (see picture5) and we address this folder to GuPPy. 
![Picture5](https://github.com/LernerLab/GuPPy/assets/138767133/1fcd9a8a-63db-45b6-a75c-d0eb809f081c)

When we lunched the step2 : Open Storenames GUI and save storenames, we obtained this error : 

['/Users/raphaelgoutaudier/Desktop/RLA8-PC_TRAINING']
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fd0ab859cf8>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/bokeh/server/session.py:51> exception=Exception('\x1b[1mColumn names should be timestamps, data and sampling_rate (all lower-cases)\x1b[0m',)>)
Traceback (most recent call last):
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/bokeh/server/session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/tornado/gen.py", line 191, in wrapper
    result = func(*args, **kwargs)
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/panel/reactive.py", line 249, in _change_coroutine
    self._change_event(doc)
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/panel/reactive.py", line 259, in _change_event
    self._process_events(events)
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/panel/reactive.py", line 242, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/param/parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/param/parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/raphaelgoutaudier/anaconda3/envs/guppy/lib/python3.6/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/raphaelgoutaudier/Documents/GuPPy-main/GuPPy/savingInputParameters.ipynb", line 321, in onclickStoresList
    "def onclickStoresList(event=None):\n",
  File "/Users/raphaelgoutaudier/Documents/GuPPy-main/GuPPy/saveStoresList.py", line 763, in execute
    event_name, flag = import_np_doric_csv(filepath, isosbestic_control, num_ch)
  File "/Users/raphaelgoutaudier/Documents/GuPPy-main/GuPPy/saveStoresList.py", line 595, in import_np_doric_csv
    raise Exception("\033[1m"+"Column names should be timestamps, data and sampling_rate (all lower-cases)"+"\033[0m")
Exception: **Column names should be timestamps, data and sampling_rate** (all lower-cases)"

We try several things. If we remove the two signal file we can go to the step2 but no storename appears. If we let the DIO files with the two column (DIO and timestamps), we can't go to the step2.

Also, we noticed that another user had a similar problem and that you adviced him to use textfile save in .csv, but for us it did not work as our text file are saved in .txt

Have you any idea about the way to solve our problem ?

**Comment by venus-sherathiya** [comment]
Can you open your csv files in notepad or normal text editor and send me the screenshots of it ?

**Comment by goutaudi** [comment]
Hello, 

I think I found the problem in my data. When I use the Matlab script to remove the useless timestamp, the new .csv file keeps only 2 number after the comma. I addition, following your recommandation I open it in notepad and I notice that all text and number in the new DIO file was "XXX.XX". This is not the same output that the initial file. 

I try to do it manually by removing each useless timestamp in excel and it works. 

![DIO01](https://github.com/LernerLab/GuPPy/assets/138767133/01d50a55-0d53-4cec-8e0a-c8cbbc386883)
![Control_DA](https://github.com/LernerLab/GuPPy/assets/138767133/eafe315e-d050-432d-b242-f81954a44b93)
![DIO02](https://github.com/LernerLab/GuPPy/assets/138767133/80b5078b-1345-49f2-bb7c-a1db590ead0a)
![DIO03](https://github.com/LernerLab/GuPPy/assets/138767133/1a1fb1c9-a512-4b19-a5d7-0b0307f3ae49)
![DIO04](https://github.com/LernerLab/GuPPy/assets/138767133/80dda54a-6d47-429b-9f75-378521a62a02)
![Signal_DA](https://github.com/LernerLab/GuPPy/assets/138767133/a753bb28-a31e-402e-9c39-30d6c5cb29e6)

**Comment by venus-sherathiya** [comment]
should I close this issue ?

**Comment by venus-sherathiya** [comment]
issue was addressed
