### ISSUE TITLE
Output folder name bug when reading raw data

### ISSUE THREAD

**Issue by MannyEsguerra** [LernerLab/GuPPy#95]
When reading raw, it seems when there's a file with a name like **Figure_ME50-240817-082218_output_1.png**, GuPPy tries to read it as an output directory. Maybe add a check for filetype?

```
Data for event Cn1/ fetched and stored.
Time taken = 0.80000
Traceback (most recent call last):
  File "D:\Packages\GuPPy-main\GuPPy\readTevTsq.py", line 556, in <module>
    raise e
  File "D:\Packages\GuPPy-main\GuPPy\readTevTsq.py", line 550, in <module>
    readRawData(json.loads(sys.argv[1]))
  File "D:\Packages\GuPPy-main\GuPPy\readTevTsq.py", line 529, in readRawData
    storesList = np.genfromtxt(os.path.join(op, 'storesList.csv'), dtype='str', delimiter=',').reshape(2,-1)
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\Windows\anaconda3\envs\guppy\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: D:\Data\Manny\Opto-GEVI IL NAcc\OptoGEVI 20240817_Pulses+Trains\ME50-240817-082218\Figure_ME50-240817-082218_output_1.png\storesList.csv not found.
```

**Comment by venus-sherathiya** [comment]
resolved the issue and pushed updated code
