### ISSUE TITLE
Error at Step 2  'utf-8'

### ISSUE THREAD

**Issue by baris-61** [LernerLab/GuPPy#98]
Hi there,
First, thank you for checking this post. Im new to GuPPy
When I select my file containing .doric file, I cant open Step 2 page and get UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 1: invalid start byte    error. What can I do to fix this issue, full error log:

Input Parameters File Saved.
['C:\\Users\\baris\\Desktop\\Doric\\test']
2024-09-23 11:54:23,711 If it exists, importing either NPM or Doric or csv file based on the structure of file
2024-09-23 11:54:23,762 'utf-8' codec can't decode byte 0x88 in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\baris\Desktop\GuPPy-main\GuPPy\saveStoresList.py", line 648, in import_np_doric_csv
    df = pd.read_csv(path[i], index_col=False, dtype=float)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 537, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 740, in pandas._libs.parsers.TextReader._get_header
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\baris\Desktop\GuPPy-main\GuPPy\saveStoresList.py", line 857, in execute
    event_name, flag = import_np_doric_csv(filepath, isosbestic_control, num_ch)
  File "C:\Users\baris\Desktop\GuPPy-main\GuPPy\saveStoresList.py", line 650, in import_np_doric_csv
    df = pd.read_csv(path[i], header=1, index_col=False, nrows=10)   # to make process faster reading just first 10 rows
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 537, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 740, in pandas._libs.parsers.TextReader._get_header
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 1: invalid start byte
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000018863EC4C40>>, <Task finished name='Task-182' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at D:\Anaconda\envs\guppy\lib\site-packages\bokeh\server\session.py:51> exception=UnicodeDecodeError('utf-8', b'?\x889L\xec\xd2\x99\x15\xc8sbg\xd9\xae|\xc8l!\xf5\xf9\x1aUSh9i\xb0b\x9er:"y_dl\xc0\xf3D\x9b\xbf\x13\xfd|-N\x9c\xc8R"4\x12\xf82\xcfG\xc7%\xa0\xf5\x7fZ\xb44\xf1\xcb\x9dy\xc47\t\xc3\xab\xc8\xf0\xc9\x82\x8b\x1f\xa8\xde\x01', 1, 2, 'invalid start byte')>)
Traceback (most recent call last):
  File "C:\Users\baris\Desktop\GuPPy-main\GuPPy\saveStoresList.py", line 648, in import_np_doric_csv
    df = pd.read_csv(path[i], index_col=False, dtype=float)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\Anaconda\envs\guppy\lib\site-packages\pandas\io\parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 537, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 740, in pandas._libs.parsers.TextReader._get_header
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

**Comment by baris-61** [comment]
Fix is you need to have only .doric files in that folder
